# Generated by Django 5.1.6 on 2025-10-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the category image'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_options',
            field=models.CharField(blank=True, help_text='Comma-separated color options', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='Product specifications in detail'),
        ),
    ]
