# Generated by Django 5.1.6 on 2025-11-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_image_url_product_color_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the banner', max_length=200)),
                ('image_url', models.URLField(help_text='URL of the banner image')),
                ('link', models.URLField(blank=True, help_text='Link to redirect when banner is clicked')),
                ('is_featured', models.BooleanField(default=False, help_text='Is this a featured banner?')),
                ('discount_info', models.CharField(blank=True, help_text='Discount information to display on the banner', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the banner in the display sequence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale_end',
            field=models.DateTimeField(blank=True, help_text='Flash sale end time', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flash sale price if applicable', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale_start',
            field=models.DateTimeField(blank=True, help_text='Flash sale start time', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock allocated for flash sale'),
        ),
    ]
