# Generated by Django 5.1.6 on 2025-11-08 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_banner_product_flash_sale_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banner'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='discount_info',
            field=models.CharField(blank=True, help_text='Thông tin giảm giá (ví dụ: Giảm 50%)', max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.URLField(help_text='URL ảnh banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Banner nổi bật (hiển thị trên carousel)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, help_text='Link khi click vào banner (tùy chọn)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text='Tiêu đề banner', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL ảnh đại diện cho danh mục (tùy chọn)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_options',
            field=models.CharField(blank=True, help_text='Danh sách màu sắc (ngăn cách bởi dấu phẩy, ví dụ: Đỏ, Xanh, Đen)', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='flash_sale_end',
            field=models.DateTimeField(blank=True, help_text='Thời gian kết thúc Flash Sale', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='flash_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Giá Flash Sale (để trống nếu không tham gia)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='flash_sale_start',
            field=models.DateTimeField(blank=True, help_text='Thời gian bắt đầu Flash Sale', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='flash_sale_stock',
            field=models.PositiveIntegerField(default=0, help_text='Số lượng dành cho Flash Sale (0 = không giới hạn riêng)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Dán URL ảnh sản phẩm (có thể lấy từ internet)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='Các thông số kỹ thuật (mỗi dòng một mục, hoặc dán dạng văn bản)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
