# Generated by Django 6.0.3 on 2026-04-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_add_popup_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='Sản phẩm bán chạy'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='Sản phẩm HOT'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Mới'), ('paid', 'Xác nhận'), ('ship', 'Đang giao'), ('done', 'Hoàn tất'), ('cancel', 'Hủy')], default='new', max_length=20),
        ),
    ]
